=== AlexandreProenca/mss/mss/agent/modules/desc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="module" type="moduleComplexType">
	</xs:element>
	<xs:element name="packages" type="packagesComplexType">
	</xs:element>
	<xs:element name="target" type="targetComplexType">
	</xs:element>
	<xs:element name="conflicts" type="conflictsComplexType">
	</xs:element>
	<xs:element name="config" type="configComplexType">
	</xs:element>
	<xs:element name="text" type="fieldTextComplexType"></xs:element>
	<xs:element name="password" type="fieldPasswordComplexType">
	</xs:element>
	<xs:element name="options" type="fieldSelectListComplexType"></xs:element>
	
	<xs:complexType name="fieldTextComplexType">
		<xs:complexContent>
			<xs:extension base="fieldBaseComplexType">
				<xs:attribute name="validation" type="xs:string" use="optional"></xs:attribute>
				<xs:attribute name="edit" type="xs:string" use="optional"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="configComplexType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="text"></xs:element>
				<xs:element ref="options"></xs:element>
				<xs:element ref="password"></xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="moduleComplexType">
		<xs:sequence>
			<xs:element minOccurs="1" name="name" type="xs:anyType">
			</xs:element>
			<xs:element minOccurs="1" name="desc" type="xs:anyType">
			</xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="actions" type="actionsComplexType"></xs:element>
			<xs:element minOccurs="1" ref="packages"></xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="deps" type="depsComplexType"></xs:element>
			<xs:element minOccurs="0" ref="conflicts"></xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="config">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="text" type="xs:anyType">
			</xs:element>
		</xs:sequence>
		<xs:attribute use="required" name="id" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="targetComplexType">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="rpm" type="xs:anyType">
			</xs:element>
		</xs:sequence>
		<xs:attribute use="required" name="name">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="all"></xs:enumeration>
					<xs:enumeration value="x86_64"></xs:enumeration>
					<xs:enumeration value="i586"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="fieldPasswordComplexType">
		<xs:complexContent>
			<xs:extension base="fieldBaseComplexType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="packagesComplexType">
		<xs:sequence>
			<xs:element minOccurs="1" ref="target"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="conflictsComplexType">
		<xs:sequence>
			<xs:element name="module" type="xs:anyType"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="fieldBaseComplexType">
		<xs:sequence>
			<xs:element minOccurs="1" name="label" type="xs:string">
			</xs:element>
			<xs:element minOccurs="0" name="help" type="xs:string">
			</xs:element>
		</xs:sequence>
		<xs:attribute use="required" name="name" type="xs:string"></xs:attribute>
		<xs:attribute use="optional" name="require">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="yes"></xs:enumeration>
					<xs:enumeration value="no"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute use="optional" name="default" type="xs:string">
		</xs:attribute>
		<xs:attribute use="optional" name="show" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="fieldSelectListComplexType">
		<xs:complexContent>
			<xs:extension base="fieldBaseComplexType">
				<xs:sequence>
					<xs:element name="option" maxOccurs="unbounded" minOccurs="2">
						<xs:complexType>
							<xs:simpleContent>
								<xs:extension base="xs:string">
									<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
								</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="actionsComplexType">
        <xs:sequence>
            <xs:element name="action" type="actionComplexType" maxOccurs="unbounded" minOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="actionComplexType">
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="link"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="value" type="xs:anyURI"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="depsComplexType">
        <xs:sequence>
            <xs:element name="module" type="xs:string" maxOccurs="unbounded" minOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== AlexandreProenca/mss/mss/agent/modules/davical/desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../desc.xsd" id="davical">
    <name>Calendar and Addressbook</name>
    <desc> DAViCal a server for calendar and addressbook sharing.</desc>
    <actions>
        <action type="link" name="Management interface" value="http://@HOSTNAME@/davical/admin.php"/>
    </actions>
    <packages>
        <target name="all">
            <rpm>davical</rpm>
            <!-- The following dependences should be inside the package. While the dependency is broken, let's install it manually -->
            <rpm>php-pdo_pgsql</rpm>
            <rpm>php-calendar</rpm>
            <rpm>php-ldap</rpm>
        </target>
    </packages>
    <deps>
<!--         <module>apache</module> -->
        <module>postgresql</module>
    </deps>
    <config>
        <text name="domain" default="get_domain" require="yes">
            <label>Domain</label>
            <help>The domain used for jabber communications</help>
        </text>
    </config>
    <text>The instant messaging service is configured.</text>
    <text>You can simply add users through the management interface at</text>
    <text>Configure clients with JID like</text>
    <text>and use</text>
    <text>as the server.</text>
    <text>If</text>
    <text>is registered as a Jabber server in the DNS zone</text>
    <text>there is no need to configure the server address in clients.</text>
</module>

=== AlexandreProenca/mss/mss/agent/modules/mds_mail/desc.xml
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../desc.xsd" id="mds_mail">
    <name>Mail service</name>
    <desc>Complete mail service with POP/IMAP, anti-virus and anti-spam toolkits</desc>
    <actions>
        <action type="link" name="Management interface" value="https://@HOSTNAME@/mmc/main.php" />
    </actions>
    <packages>
        <target name="all">
            <rpm>postfix</rpm>
            <rpm>postfix-ldap</rpm>
            <rpm>mmc-web-mail</rpm>
            <rpm>python-mmc-mail</rpm>
            <rpm>amavisd-new</rpm>
            <rpm>spamassassin</rpm>
            <rpm>spamassassin-tools</rpm>
            <rpm>clamd</rpm>
            <rpm>dovecot</rpm>
            <rpm>dovecot-plugins-ldap</rpm>
            <rpm>dovecot-plugins-sieve</rpm>
            <rpm>dovecot-plugins-managesieve</rpm>
        </target>
    </packages>
    <conflicts>
        <module>zarafa</module>
    </conflicts>
    <deps>
        <module>mds_mmc</module>
    </deps>
    <config>
        <network name="smtpd_mynetworks" format="short" validation="network" default="get_networks">
            <label>My networks</label>
            <help>Specify which clients are authorized to send mails through the mail server without authentication.</help>
        </network>
        <options name="popimap_proto" require="yes">
            <label>Protocols supported</label>
            <help>Protocols that the dovecot server will provide.</help>
            <option value="imap imaps pop3 pop3s">IMAPS and POP3S</option>
            <option value="imaps imap">IMAPS</option>
            <option value="pop3 pop3s">POP3S</option>
        </options>
        <check name="fw_lan" default="on">
            <label>Allow mail services access from internal networks</label>
            <help>Configure the firewall to accept smtp/imap/pop3 connections
                on interfaces configured as 'internal'</help>
        </check>
        <check name="fw_wan" default="off">
            <label>Allow mail services access from external networks</label>
            <help>Configure the firewall to accept smtp/imap/pop3 connections
                on interfaces configured as 'external'</help>
        </check>
    </config>
</module>

=== AlexandreProenca/mss/mss/agent/modules/mds_quota/desc.xml
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../desc.xsd" id="mds_quota">
    <name>User quota management</name>
    <desc>Set file quotas on the server</desc>
    <packages>
        <target name="all">
            <rpm>quota</rpm>
            <rpm>python-mmc-userquota</rpm>
            <rpm>mmc-web-userquota</rpm>
        </target>
    </packages>
    <deps>
        <module>mds_mmc</module>
    </deps>
    <config>
        <text name="filesystems" require="yes" default="get_filesystems" multi="yes">
            <label>Filesystems</label>
            <help>Specify the filesystems where you want to apply user quotas with the following format : "Device path":"Identifier string" (eg: /dev/sda1:Root)</help>
        </text>
    </config>
</module>

=== AlexandreProenca/mss/mss/agent/modules/mds_smb/desc.xml
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../desc.xsd" id="mds_smb">
    <name>Windows users and file sharing management</name>
    <desc>Authenticate Windows users with SAMBA and provide Windows file shares on your network</desc>
    <actions>
        <action type="link" name="Management interface" value="https://@HOSTNAME@/mmc/main.php" />
    </actions>
    <packages>
        <target name="all">
            <rpm>samba-server</rpm>
            <rpm>samba-client</rpm>
            <rpm>samba-common</rpm>
            <rpm>samba-doc</rpm>
            <rpm>smbldap-tools</rpm>
            <rpm>mmc-web-samba</rpm>
            <rpm>python-mmc-samba</rpm>
        </target>
    </packages>
    <deps>
        <module>mds_mmc</module>
    </deps>
    <config>
        <text name="smbdomain" require="yes" default="MBSDOMAIN"
            validation="valid_domain">
            <label>SAMBA domain name</label>
            <help>The name of your Microsoft domain.</help>
        </text>
        <text name="smbnetbios" require="yes" default="get_netbios"
            validation="valid_netbios">
            <label>Netbios name</label>
            <help>The name of your SAMBA server in the Microsoft domain.</help>
        </text>
        <text name="smbadmin" require="yes" default="admin">
            <label>Administrator name</label>
            <help>The name of the Microsoft domain administrator.</help>
        </text>
        <password name="smbpasswd" require="yes">
            <label>Administrator password</label>
            <help>Password for the Microsoft domain administrator.</help>
        </password>
        <check name="fw_lan" default="on">
            <label>Allow connections from internal networks</label>
            <help>Configure the firewall to accept SAMBA related traffic on interfaces
                configured as 'internal'</help>
        </check>
        <check name="fw_wan" default="off">
            <label>Allow connections connections external networks</label>
            <help>Configure the firewall to accept SAMBA related traffic on interfaces
                configured as 'external'</help>
        </check>
    </config>
</module>

=== AlexandreProenca/mss/mss/agent/modules/mds_cups/desc.xml
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../desc.xsd" id="mds_cups">
    <name>Printing service</name>
    <desc>Network printers management</desc>
    <actions>
        <action type="link" name="Printers management" value="http://@HOSTNAME@:631/admin/" />
    </actions>
    <packages>
        <target name="all">
            <rpm>cups</rpm>
            <rpm>cups-drivers</rpm>
            <rpm>cups-windows</rpm>
            <rpm>foomatic-filters</rpm>
            <rpm>hplip-hpijs-ppds</rpm>
            <rpm>postscript-ppds</rpm>
            <rpm>hplip</rpm>
        </target>
    </packages>
    <config>
        <check name="fw_lan" default="on">
            <label>Allow connections to the management interface from internal networks</label>
            <help>Configure the firewall to accept connections on the Cups
                interface from interfaces configured as 'internal'</help>
        </check>
        <check name="fw_wan" default="off">
            <label>Allow connections to the management interface from external networks</label>
            <help>Configure the firewall to accept connections on the Cups
                interface from interfaces configured as 'external'</help>
        </check>
    </config>
    <text>The printing service is running.</text>
    <text>You can add new printers from the Cups web interface : https://@HOSTNAME@:631/admin/</text>
    <text>Login to the Cups interface is the root account.</text>
</module>

=== AlexandreProenca/mss/mss/agent/modules/mds_webmail/desc.xml
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../desc.xsd" id="mds_webmail">
    <name>Webmail</name>
    <desc>Roundcube, a complete webmail solution for your mail service</desc>
    <actions>
        <action type="link" name="Management interface" value="https://@HOSTNAME@/mmc/main.php" />
        <action type="link" name="Webmail interface" value="https://@HOSTNAME@/roundcubemail/" />
    </actions>
    <packages>
        <target name="all">
            <rpm>roundcubemail</rpm>
            <rpm>sqlite-tools</rpm>
            <rpm>php-fileinfo</rpm>
            <rpm>php-mcrypt</rpm>
            <rpm>php-pear-MDB2_Driver_sqlite</rpm>
        </target>
    </packages>
    <deps>
        <module>mds_mail</module>
    </deps>
    <conflicts>
        <module>zarafa</module>
    </conflicts>
    <config>
        <check name="fw_lan" default="on">
            <label>Allow access from internal networks</label>
            <help>Configure the firewall to allow access to the webmail
                interface from internal networks</help>
        </check>
        <check name="fw_wan" default="on">
            <label>Allow access from external networks</label>
            <help>Configure the firewall to allow access to the webmail
                interface from external networks</help>
        </check>
    </config>
    <text>Webmail RoundCube is activated on your server.</text>
    <text>You can access the webmail interface at https://@HOSTNAME@/roundcubemail/</text>
</module>
